// Generated by the protocol buffer compiler.  DO NOT EDIT!

package man;

public final class Structs {
  private Structs() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\rstructs.proto\022\003man\"\035\n\005Point\022\t\n\001x\030\001 \002(\005" +
      "\022\t\n\001y\030\002 \002(\005\"\207\001\n\tRectangle\022\033\n\007leftTop\030\001 \002" +
      "(\0132\n.man.Point\022\034\n\010rightTop\030\002 \002(\0132\n.man.P" +
      "oint\022\036\n\nleftBottom\030\003 \002(\0132\n.man.Point\022\037\n\013" +
      "rightBottom\030\004 \002(\0132\n.man.Point";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"structs.proto\".", e);
    }
  }
  
  public static final class Point extends
      com.google.protobuf.GeneratedMessage {
    // Use Point.newBuilder() to construct.
    private Point() {}
    
    private static final Point defaultInstance = new Point();
    public static Point getDefaultInstance() {
      return defaultInstance;
    }
    
    public Point getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return man.Structs.internal_static_man_Point_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return man.Structs.internal_static_man_Point_fieldAccessorTable;
    }
    
    // required int32 x = 1;
    private boolean hasX;
    private int x_ = 0;
    public boolean hasX() { return hasX; }
    public int getX() { return x_; }
    
    // required int32 y = 2;
    private boolean hasY;
    private int y_ = 0;
    public boolean hasY() { return hasY; }
    public int getY() { return y_; }
    
    public static man.Structs.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static man.Structs.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static man.Structs.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static man.Structs.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static man.Structs.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(man.Structs.Point prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using man.Structs.Point.newBuilder()
      private Builder() {}
      
      man.Structs.Point result = new man.Structs.Point();
      
      protected man.Structs.Point internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new man.Structs.Point();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return man.Structs.Point.getDescriptor();
      }
      
      public man.Structs.Point getDefaultInstanceForType() {
        return man.Structs.Point.getDefaultInstance();
      }
      
      public man.Structs.Point build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private man.Structs.Point buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public man.Structs.Point buildPartial() {
        man.Structs.Point returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int32 x = 1;
      public boolean hasX() {
        return result.hasX();
      }
      public int getX() {
        return result.getX();
      }
      public Builder setX(int value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0;
        return this;
      }
      
      // required int32 y = 2;
      public boolean hasY() {
        return result.hasY();
      }
      public int getY() {
        return result.getY();
      }
      public Builder setY(int value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0;
        return this;
      }
    }
  }
  
  public static final class Rectangle extends
      com.google.protobuf.GeneratedMessage {
    // Use Rectangle.newBuilder() to construct.
    private Rectangle() {}
    
    private static final Rectangle defaultInstance = new Rectangle();
    public static Rectangle getDefaultInstance() {
      return defaultInstance;
    }
    
    public Rectangle getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return man.Structs.internal_static_man_Rectangle_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return man.Structs.internal_static_man_Rectangle_fieldAccessorTable;
    }
    
    // required .man.Point leftTop = 1;
    private boolean hasLeftTop;
    private man.Structs.Point leftTop_ = man.Structs.Point.getDefaultInstance();
    public boolean hasLeftTop() { return hasLeftTop; }
    public man.Structs.Point getLeftTop() { return leftTop_; }
    
    // required .man.Point rightTop = 2;
    private boolean hasRightTop;
    private man.Structs.Point rightTop_ = man.Structs.Point.getDefaultInstance();
    public boolean hasRightTop() { return hasRightTop; }
    public man.Structs.Point getRightTop() { return rightTop_; }
    
    // required .man.Point leftBottom = 3;
    private boolean hasLeftBottom;
    private man.Structs.Point leftBottom_ = man.Structs.Point.getDefaultInstance();
    public boolean hasLeftBottom() { return hasLeftBottom; }
    public man.Structs.Point getLeftBottom() { return leftBottom_; }
    
    // required .man.Point rightBottom = 4;
    private boolean hasRightBottom;
    private man.Structs.Point rightBottom_ = man.Structs.Point.getDefaultInstance();
    public boolean hasRightBottom() { return hasRightBottom; }
    public man.Structs.Point getRightBottom() { return rightBottom_; }
    
    public static man.Structs.Rectangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static man.Structs.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(man.Structs.Rectangle prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using man.Structs.Rectangle.newBuilder()
      private Builder() {}
      
      man.Structs.Rectangle result = new man.Structs.Rectangle();
      
      protected man.Structs.Rectangle internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new man.Structs.Rectangle();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return man.Structs.Rectangle.getDescriptor();
      }
      
      public man.Structs.Rectangle getDefaultInstanceForType() {
        return man.Structs.Rectangle.getDefaultInstance();
      }
      
      public man.Structs.Rectangle build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private man.Structs.Rectangle buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public man.Structs.Rectangle buildPartial() {
        man.Structs.Rectangle returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .man.Point leftTop = 1;
      public boolean hasLeftTop() {
        return result.hasLeftTop();
      }
      public man.Structs.Point getLeftTop() {
        return result.getLeftTop();
      }
      public Builder setLeftTop(man.Structs.Point value) {
        result.hasLeftTop = true;
        result.leftTop_ = value;
        return this;
      }
      public Builder setLeftTop(man.Structs.Point.Builder builderForValue) {
        result.hasLeftTop = true;
        result.leftTop_ = builderForValue.build();
        return this;
      }
      public Builder mergeLeftTop(man.Structs.Point value) {
        if (result.hasLeftTop() &&
            result.leftTop_ != man.Structs.Point.getDefaultInstance()) {
          result.leftTop_ =
            man.Structs.Point.newBuilder(result.leftTop_).mergeFrom(value).buildPartial();
        } else {
          result.leftTop_ = value;
        }
        result.hasLeftTop = true;
        return this;
      }
      public Builder clearLeftTop() {
        result.hasLeftTop = false;
        result.leftTop_ = man.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .man.Point rightTop = 2;
      public boolean hasRightTop() {
        return result.hasRightTop();
      }
      public man.Structs.Point getRightTop() {
        return result.getRightTop();
      }
      public Builder setRightTop(man.Structs.Point value) {
        result.hasRightTop = true;
        result.rightTop_ = value;
        return this;
      }
      public Builder setRightTop(man.Structs.Point.Builder builderForValue) {
        result.hasRightTop = true;
        result.rightTop_ = builderForValue.build();
        return this;
      }
      public Builder mergeRightTop(man.Structs.Point value) {
        if (result.hasRightTop() &&
            result.rightTop_ != man.Structs.Point.getDefaultInstance()) {
          result.rightTop_ =
            man.Structs.Point.newBuilder(result.rightTop_).mergeFrom(value).buildPartial();
        } else {
          result.rightTop_ = value;
        }
        result.hasRightTop = true;
        return this;
      }
      public Builder clearRightTop() {
        result.hasRightTop = false;
        result.rightTop_ = man.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .man.Point leftBottom = 3;
      public boolean hasLeftBottom() {
        return result.hasLeftBottom();
      }
      public man.Structs.Point getLeftBottom() {
        return result.getLeftBottom();
      }
      public Builder setLeftBottom(man.Structs.Point value) {
        result.hasLeftBottom = true;
        result.leftBottom_ = value;
        return this;
      }
      public Builder setLeftBottom(man.Structs.Point.Builder builderForValue) {
        result.hasLeftBottom = true;
        result.leftBottom_ = builderForValue.build();
        return this;
      }
      public Builder mergeLeftBottom(man.Structs.Point value) {
        if (result.hasLeftBottom() &&
            result.leftBottom_ != man.Structs.Point.getDefaultInstance()) {
          result.leftBottom_ =
            man.Structs.Point.newBuilder(result.leftBottom_).mergeFrom(value).buildPartial();
        } else {
          result.leftBottom_ = value;
        }
        result.hasLeftBottom = true;
        return this;
      }
      public Builder clearLeftBottom() {
        result.hasLeftBottom = false;
        result.leftBottom_ = man.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .man.Point rightBottom = 4;
      public boolean hasRightBottom() {
        return result.hasRightBottom();
      }
      public man.Structs.Point getRightBottom() {
        return result.getRightBottom();
      }
      public Builder setRightBottom(man.Structs.Point value) {
        result.hasRightBottom = true;
        result.rightBottom_ = value;
        return this;
      }
      public Builder setRightBottom(man.Structs.Point.Builder builderForValue) {
        result.hasRightBottom = true;
        result.rightBottom_ = builderForValue.build();
        return this;
      }
      public Builder mergeRightBottom(man.Structs.Point value) {
        if (result.hasRightBottom() &&
            result.rightBottom_ != man.Structs.Point.getDefaultInstance()) {
          result.rightBottom_ =
            man.Structs.Point.newBuilder(result.rightBottom_).mergeFrom(value).buildPartial();
        } else {
          result.rightBottom_ = value;
        }
        result.hasRightBottom = true;
        return this;
      }
      public Builder clearRightBottom() {
        result.hasRightBottom = false;
        result.rightBottom_ = man.Structs.Point.getDefaultInstance();
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_man_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_man_Point_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_man_Point_descriptor,
          new java.lang.String[] { "X", "Y", },
          man.Structs.Point.class,
          man.Structs.Point.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_man_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_man_Rectangle_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_man_Rectangle_descriptor,
          new java.lang.String[] { "LeftTop", "RightTop", "LeftBottom", "RightBottom", },
          man.Structs.Rectangle.class,
          man.Structs.Rectangle.Builder.class);
}
