// Generated by the protocol buffer compiler.  DO NOT EDIT!

package bites;

public final class Structs {
  private Structs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Point extends
      com.google.protobuf.GeneratedMessage {
    // Use Point.newBuilder() to construct.
    private Point() {}
    
    private static final Point defaultInstance = new Point();
    public static Point getDefaultInstance() {
      return defaultInstance;
    }
    
    public Point getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bites.Structs.internal_static_bites_Point_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bites.Structs.internal_static_bites_Point_fieldAccessorTable;
    }
    
    // required int32 x = 1;
    private boolean hasX;
    private int x_ = 0;
    public boolean hasX() { return hasX; }
    public int getX() { return x_; }
    
    // required int32 y = 2;
    private boolean hasY;
    private int y_ = 0;
    public boolean hasY() { return hasY; }
    public int getY() { return y_; }
    
    public static bites.Structs.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bites.Structs.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bites.Structs.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bites.Structs.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bites.Structs.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bites.Structs.Point prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bites.Structs.Point.newBuilder()
      private Builder() {}
      
      bites.Structs.Point result = new bites.Structs.Point();
      
      @Override
      protected bites.Structs.Point internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new bites.Structs.Point();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bites.Structs.Point.getDescriptor();
      }
      
      public bites.Structs.Point getDefaultInstanceForType() {
        return bites.Structs.Point.getDefaultInstance();
      }
      
      public bites.Structs.Point build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bites.Structs.Point buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bites.Structs.Point buildPartial() {
        bites.Structs.Point returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int32 x = 1;
      public boolean hasX() {
        return result.hasX();
      }
      public int getX() {
        return result.getX();
      }
      public Builder setX(int value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0;
        return this;
      }
      
      // required int32 y = 2;
      public boolean hasY() {
        return result.hasY();
      }
      public int getY() {
        return result.getY();
      }
      public Builder setY(int value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0;
        return this;
      }
    }
    
    static {
      bites.Structs.getDescriptor();
    }
  }
  
  public static final class Rectangle extends
      com.google.protobuf.GeneratedMessage {
    // Use Rectangle.newBuilder() to construct.
    private Rectangle() {}
    
    private static final Rectangle defaultInstance = new Rectangle();
    public static Rectangle getDefaultInstance() {
      return defaultInstance;
    }
    
    public Rectangle getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bites.Structs.internal_static_bites_Rectangle_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bites.Structs.internal_static_bites_Rectangle_fieldAccessorTable;
    }
    
    // required .bites.Point leftTop = 1;
    private boolean hasLeftTop;
    private bites.Structs.Point leftTop_ = bites.Structs.Point.getDefaultInstance();
    public boolean hasLeftTop() { return hasLeftTop; }
    public bites.Structs.Point getLeftTop() { return leftTop_; }
    
    // required .bites.Point rightTop = 2;
    private boolean hasRightTop;
    private bites.Structs.Point rightTop_ = bites.Structs.Point.getDefaultInstance();
    public boolean hasRightTop() { return hasRightTop; }
    public bites.Structs.Point getRightTop() { return rightTop_; }
    
    // required .bites.Point leftBottom = 3;
    private boolean hasLeftBottom;
    private bites.Structs.Point leftBottom_ = bites.Structs.Point.getDefaultInstance();
    public boolean hasLeftBottom() { return hasLeftBottom; }
    public bites.Structs.Point getLeftBottom() { return leftBottom_; }
    
    // required .bites.Point rightBottom = 4;
    private boolean hasRightBottom;
    private bites.Structs.Point rightBottom_ = bites.Structs.Point.getDefaultInstance();
    public boolean hasRightBottom() { return hasRightBottom; }
    public bites.Structs.Point getRightBottom() { return rightBottom_; }
    
    public static bites.Structs.Rectangle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static bites.Structs.Rectangle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(bites.Structs.Rectangle prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using bites.Structs.Rectangle.newBuilder()
      private Builder() {}
      
      bites.Structs.Rectangle result = new bites.Structs.Rectangle();
      
      @Override
      protected bites.Structs.Rectangle internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new bites.Structs.Rectangle();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bites.Structs.Rectangle.getDescriptor();
      }
      
      public bites.Structs.Rectangle getDefaultInstanceForType() {
        return bites.Structs.Rectangle.getDefaultInstance();
      }
      
      public bites.Structs.Rectangle build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private bites.Structs.Rectangle buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public bites.Structs.Rectangle buildPartial() {
        bites.Structs.Rectangle returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .bites.Point leftTop = 1;
      public boolean hasLeftTop() {
        return result.hasLeftTop();
      }
      public bites.Structs.Point getLeftTop() {
        return result.getLeftTop();
      }
      public Builder setLeftTop(bites.Structs.Point value) {
        result.hasLeftTop = true;
        result.leftTop_ = value;
        return this;
      }
      public Builder setLeftTop(bites.Structs.Point.Builder builderForValue) {
        result.hasLeftTop = true;
        result.leftTop_ = builderForValue.build();
        return this;
      }
      public Builder mergeLeftTop(bites.Structs.Point value) {
        if (result.hasLeftTop() &&
            result.leftTop_ != bites.Structs.Point.getDefaultInstance()) {
          result.leftTop_ =
            bites.Structs.Point.newBuilder(result.leftTop_).mergeFrom(value).buildPartial();
        } else {
          result.leftTop_ = value;
        }
        result.hasLeftTop = true;
        return this;
      }
      public Builder clearLeftTop() {
        result.hasLeftTop = false;
        result.leftTop_ = bites.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .bites.Point rightTop = 2;
      public boolean hasRightTop() {
        return result.hasRightTop();
      }
      public bites.Structs.Point getRightTop() {
        return result.getRightTop();
      }
      public Builder setRightTop(bites.Structs.Point value) {
        result.hasRightTop = true;
        result.rightTop_ = value;
        return this;
      }
      public Builder setRightTop(bites.Structs.Point.Builder builderForValue) {
        result.hasRightTop = true;
        result.rightTop_ = builderForValue.build();
        return this;
      }
      public Builder mergeRightTop(bites.Structs.Point value) {
        if (result.hasRightTop() &&
            result.rightTop_ != bites.Structs.Point.getDefaultInstance()) {
          result.rightTop_ =
            bites.Structs.Point.newBuilder(result.rightTop_).mergeFrom(value).buildPartial();
        } else {
          result.rightTop_ = value;
        }
        result.hasRightTop = true;
        return this;
      }
      public Builder clearRightTop() {
        result.hasRightTop = false;
        result.rightTop_ = bites.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .bites.Point leftBottom = 3;
      public boolean hasLeftBottom() {
        return result.hasLeftBottom();
      }
      public bites.Structs.Point getLeftBottom() {
        return result.getLeftBottom();
      }
      public Builder setLeftBottom(bites.Structs.Point value) {
        result.hasLeftBottom = true;
        result.leftBottom_ = value;
        return this;
      }
      public Builder setLeftBottom(bites.Structs.Point.Builder builderForValue) {
        result.hasLeftBottom = true;
        result.leftBottom_ = builderForValue.build();
        return this;
      }
      public Builder mergeLeftBottom(bites.Structs.Point value) {
        if (result.hasLeftBottom() &&
            result.leftBottom_ != bites.Structs.Point.getDefaultInstance()) {
          result.leftBottom_ =
            bites.Structs.Point.newBuilder(result.leftBottom_).mergeFrom(value).buildPartial();
        } else {
          result.leftBottom_ = value;
        }
        result.hasLeftBottom = true;
        return this;
      }
      public Builder clearLeftBottom() {
        result.hasLeftBottom = false;
        result.leftBottom_ = bites.Structs.Point.getDefaultInstance();
        return this;
      }
      
      // required .bites.Point rightBottom = 4;
      public boolean hasRightBottom() {
        return result.hasRightBottom();
      }
      public bites.Structs.Point getRightBottom() {
        return result.getRightBottom();
      }
      public Builder setRightBottom(bites.Structs.Point value) {
        result.hasRightBottom = true;
        result.rightBottom_ = value;
        return this;
      }
      public Builder setRightBottom(bites.Structs.Point.Builder builderForValue) {
        result.hasRightBottom = true;
        result.rightBottom_ = builderForValue.build();
        return this;
      }
      public Builder mergeRightBottom(bites.Structs.Point value) {
        if (result.hasRightBottom() &&
            result.rightBottom_ != bites.Structs.Point.getDefaultInstance()) {
          result.rightBottom_ =
            bites.Structs.Point.newBuilder(result.rightBottom_).mergeFrom(value).buildPartial();
        } else {
          result.rightBottom_ = value;
        }
        result.hasRightBottom = true;
        return this;
      }
      public Builder clearRightBottom() {
        result.hasRightBottom = false;
        result.rightBottom_ = bites.Structs.Point.getDefaultInstance();
        return this;
      }
    }
    
    static {
      bites.Structs.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bites_Point_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bites_Point_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bites_Rectangle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bites_Rectangle_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\rstructs.proto\022\005bites\"\035\n\005Point\022\t\n\001x\030\001 \002" +
      "(\005\022\t\n\001y\030\002 \002(\005\"\217\001\n\tRectangle\022\035\n\007leftTop\030\001" +
      " \002(\0132\014.bites.Point\022\036\n\010rightTop\030\002 \002(\0132\014.b" +
      "ites.Point\022 \n\nleftBottom\030\003 \002(\0132\014.bites.P" +
      "oint\022!\n\013rightBottom\030\004 \002(\0132\014.bites.Point";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_bites_Point_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_bites_Point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bites_Point_descriptor,
              new java.lang.String[] { "X", "Y", },
              bites.Structs.Point.class,
              bites.Structs.Point.Builder.class);
          internal_static_bites_Rectangle_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_bites_Rectangle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_bites_Rectangle_descriptor,
              new java.lang.String[] { "LeftTop", "RightTop", "LeftBottom", "RightBottom", },
              bites.Structs.Rectangle.class,
              bites.Structs.Rectangle.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
